[workspace]
name = "pvactools-pvacseq-linux-x86_64-cpu"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
setuptools = "80.9.0.*"
tensorflow = "2.15.*"
numpy = "1.26.4.*"
pandas = ">=1.5,<2.1"
scikit-learn = ">=1.6,<1.8"
requests = "*"
pyyaml = "*"
biopython = "1.83.*"
networkx = "*"
simanneal = "*"
python-wget = "3.2.*"
pysam = "*"
pillow = "*"
pymp-pypi = "*"
mock = "*"
testfixtures = "*"
gtfparse = "2.0.1.*"
pyfaidx = ">=0.7.1"
fsspec = "<=2025.3.0"
packaging = "*"
pyarrow = "*"
polars = "0.16.18.*"
xlsxwriter = "*"
openpyxl = "*"
deepdiff = "*"
imbalanced-learn = "*"
appdirs = "*"
tqdm = "*"
six = "*"
